### ISSUE TITLE
Plugin component missing for authenticator sso, this is an error.

### ISSUE THREAD

**Issue by brettlangdon** [Graylog2/graylog-plugin-auth-sso#12]
### Problem description

When viewing the configuration settings for SSO, only seeing an error:

```
Plugin component missing for authenticator sso, this is an error.
```

I am assuming there is a requirement that I am missing somewhere.

### Screenshot

![image](https://cloud.githubusercontent.com/assets/1320353/18205021/d234268c-70ed-11e6-9556-02a1fc5295b9.png)

### Steps to reproduce the problem

* Install the latest version of the plugin via `.deb` package
```bash
wget https://github.com/Graylog2/graylog-plugin-auth-sso/releases/download/1.0.1/graylog-plugin-auth-sso-1.0.1.deb
dpkg -i graylog-plugin-auth-sso-1.0.1.deb
service graylog-server restart
```
* Open SSO authentication configuration page, `http://localhost/system/authentication/config/sso`

### Environment

* Graylog Version:
  * UI shows `Graylog 2.1.0+62db7e0`
  * `dpkg` shows
    * `ii  graylog-server                       2.1.0-9                          all          Graylog server`
* Plugin Version: `1.0.1`
* Elasticsearch Version: `2.3.1`
* MongoDB Version: `2.4.9`
* Operating System: `Ubuntu 14.04`
* Browser version: `Chrome 52.0.2743.116`

**Comment by hc4** [comment]
Looks like release build broken.
Because normally sso plugin size should be 800KB.
As I understand, plugin must contain copy of graylog UI components inside.

Released jar size is just about 20KB. So I think it missing UI components, and thus it can't render UI.

**Comment by hc4** [comment]
As a workaround you could configure plugin throught REST API.
Plugin itself should work correctly even without UI :)

**Comment by AlekseyChudov** [comment]
The same for RPM package
# l /usr/share/graylog-server/plugin/graylog-plugin-auth-sso-1.0.1.jar
-rw-r--r--. 1 root root 20240 Sep  1 19:32 /usr/share/graylog-server/plugin/graylog-plugin-auth-sso-1.0.1.jar

**Comment by quetzal** [comment]
The same for the deb package. All the builds seem brokens.

**Comment by towolf** [comment]
We've had double auth for Graylog for a long time. Happy to hear we can integrate our SSO now.

Just, it doesn't work ...

**Comment by hc4** [comment]
it work, but you should manualy config it throught REST api (e.g. use API browser)

**Comment by towolf** [comment]
Can you give example curl lines, how to do it via the API?

**Comment by jalogisch** [comment]
Please use the latest release: https://github.com/Graylog2/graylog-plugin-auth-sso/releases/tag/1.0.3 the Error is fixed.

**Comment by twall** [comment]
I'm seeing this issue on the 2.4.2 release.

**Comment by wmkwood** [comment]
Graylog 3.0 beta as well.
graylog-plugin-auth-sso-2.5.1-1.noarch
