### ISSUE TITLE
Plugin does not recognize graylog install on appliance

### ISSUE THREAD

**Issue by kalendubrick** [Graylog2/graylog-plugin-auth-sso#14]
### Problem description

The .deb installer for the plugin does not recognize that the graylog package is installed and errors out.
### Steps to reproduce the problem
1. Setup graylog appliance via OVA (ours started on 1.x, then upgraded to 2.0, and now to 2.1)
2. Attempt to install deb (`dpkg -G -I graylog-plugin-auth-sso-1.0.3.deb`)
3. Receive the following output:

```
Preparing to unpack graylog-plugin-auth-sso-1.0.3.deb ...
Unpacking graylog-plugin-auth-sso (1.0.3) over (1.0.3) ...
dpkg: dependency problems prevent configuration of graylog-plugin-auth-sso:
 graylog-plugin-auth-sso depends on graylog-server | graylog-radio; however:
  Package graylog-server is not installed.
  Package graylog-radio is not installed.

dpkg: error processing package graylog-plugin-auth-sso (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 graylog-plugin-auth-sso
```

Graylog is installed.  It appears the plugin is looking for graylog-server, but the package for 2.1 reports itself as `graylog`:

```
ubuntu@graylog:~$ dpkg -l | grep graylog
ii  graylog                             2.1.0-1                          amd64        The full stack of graylog
iU  graylog-plugin-auth-sso             1.0.3                            all          Graylog graylog-plugin-auth-sso plugin.
```
### Environment
- Graylog Version: 2.1.0+62db7e0
- Plugin Version: 1.0.3
- Elasticsearch Version: 2.3.1
- MongoDB Version: Not sure how to determine this on appliance (`mongod` package is not installed)
- Operating System: Ubuntu (whichever version the appliance ships with - 12.04?)  Client is Windows 10 Enterprise
- Browser version: Chrome 53

**Comment by jalogisch** [comment]
@kalendubrick please - as a quick fix - use the .jar from the release page: https://github.com/Graylog2/graylog-plugin-auth-sso/releases/download/1.0.3/graylog-plugin-auth-sso-1.0.3.jar

and place put it manual into the plugin folder (default folders are documented here: http://docs.graylog.org/en/2.1/pages/configuration/file_location.html#omnibus-package )

We will not create a .deb for the appliance but need to document this in the readme and the documentation.

**Comment by joschi** [comment]
The plugin installation for the Omnibus package is described at http://docs.graylog.org/en/2.1/pages/configuration/graylog_ctl.html#install-graylog-plugins. The provided DEB packages for plugins only work with the [Graylog OS packages](http://docs.graylog.org/en/2.1/pages/installation/operating_system_packages.html).
