### ISSUE TITLE
Make possible to authenticate by email only

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog-plugin-auth-sso#2]
Make possible to authenticate by email only

**Comment by kroepke** [comment]
Do you mean just having a header that contains the email address and then using that as the user name?

**Comment by hc4** [comment]
I want sso to authorize user by email, i.e. find it by email in db.

**Comment by joschi** [comment]
@hc4 Please describe the workflow in a little more detail.

Which component exactly would lookup the email address of the user in some database?

**Comment by hc4** [comment]
I want to pass only user email to sso plugin, and it should find this user by email and authorize.
[Here ](https://github.com/Graylog2/graylog-plugin-auth-sso/blob/master/src/main/java/org/graylog/plugins/auth/sso/SsoAuthRealm.java#L100) in code user lookedup by name, but my idea to make also logic to lookup user by email only.

**Comment by hc4** [comment]
In other words I want to pass only user email with header to SsoAuthRealm and it should correctly find this user and authorize.

**Comment by joschi** [comment]
@hc4 What would happen if multiple users have the same email address in Graylog's user database? Currently they don't need to be unique.

**Comment by hc4** [comment]
hm. this is problem. I thought users can't have same email :)
But anyway - if there is multiple users with same email - SsoAuth may log error about ambiguouty and don't authorize user

**Comment by jalogisch** [comment]
we will not implement this.

if you like to have such edge case, please build your own auth plugin.
