### ISSUE TITLE
make it compatible with 2.3

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog-plugin-auth-sso#27]
### Problem description
when you install the current release into 2.3.0 beta 1 you only get the following warning:

`Plugin component missing for authenticator sso, this is an error.`

### Steps to reproduce the problem

1. install the release 1.0.6 on graylog 2.3.beta.1
2. go to `System > authentication > sso`

**Comment by bernd** [comment]
Done with version 2.3.0.
