### ISSUE TITLE
Shibboleth SSO and API Tokens

### ISSUE THREAD

**Issue by TheRealKingS** [Graylog2/graylog-plugin-auth-sso#30]
### Problem description
We are using Shibboleth with this SSO Plugin. It works so far, but if i try to login via API-Token, i get an Redirect to Shibboleth. Is there any chance to use API Tokens and Shibboleth together? 

Apache configuration:

```
<VirtualHost *:443>
    ServerName graylog.example.com
    ProxyRequests Off

    SSLEngine on
    SSLCertificateFile /etc/httpd/ssl/ssl.crt
    SSLCertificateKeyFile /etc/httpd/ssl/ssl.key
    SSLCertificateChainFile /etc/httpd/ssl/chain.txt

    <Proxy *>
      Order deny,allow
      Allow from all
    </Proxy>

    <Location />
        RequestHeader set X-Graylog-Server-URL "https://graylog.example.com/api/"
        ProxyPass http://127.0.0.1:9000/
        ProxyPassReverse http://127.0.0.1:9000/
        AuthType shibboleth
        ShibRequestSetting requireSession 1
        ShibUseHeaders On
        require valid-user
    </Location>
```

### Steps to reproduce the problem

1. Configure Shibboleth and the plugin
2. generate API Token for an user
3. Try to query the api

### Environment

* Graylog Version: 2.3.1
* Plugin Version: 2.3.0
* Elasticsearch Version: 2.4.6
* MongoDB Version: 3.2.16
* Operating System: centos 7
* Browser Version: Chrome Version 60.0.3112.113

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
