### ISSUE TITLE
can't get it to work with gl-2.3.1

### ISSUE THREAD

**Issue by jhaar** [Graylog2/graylog-plugin-auth-sso#31]
### Problem description
I have configured it according to the docs. It shows up after API tokens and before LDAP and Password providers. I've configured headers for uid, email and configured it for automatic creation and whitelisted our reverse proxy IP

But when I hit our reverse proxy, I still end up on the GL login page. tcpdump shows the correct headers are being sent - but they seem to be ignored

Are there limitations on the headers? eg I'm using "X-MELLON_uid" for the username header

Is there a particular graylog URI I could hit via curl that would force a login and perhaps point out why this isn't working?

Thanks

### Environment

* Graylog Version: 2.3.1
* Plugin Version: 2.3.0
* Elasticsearch Version:
* MongoDB Version:
* Operating System: centos-7
* Browser version: firefox

**Comment by minhdanh** [comment]
I can't get this plugin work with graylog 2.4.6 either.
The login page of Graylog still being shown after the proxy has forwarded the request to Graylog.
I have checked the headers passed from the proxy, there were `x-forwarded-email` and `x-forwarded-user` which were configured correctly in the SSO settings page.

### Environment:
- Graylog: 2.4.6
- Plugin versiion: 2.4.2

**Comment by bernd** [comment]
This issue has been opened for an old version of Graylog. The SSO plugin is deprecated, and parts of its features are in the Graylog server now. I am closing the issue.
