### ISSUE TITLE
Add Support for ADFS SSO (SAML)

### ISSUE THREAD

**Issue by dnauck** [Graylog2/graylog-plugin-auth-sso#34]
It would be nice if this plugin also supports the ADFS Single Sign On (like Office 365 and others).

**Comment by jalogisch** [comment]
We would welcome any PR on this topic, but it is not very likely that we will implement this.

**Comment by florianvolle** [comment]
Closing this as we are not planing to implement this. As @jalogisch said you are welcome to provide a PR for this.
Thanks!
