### ISSUE TITLE
Remove profile web-interface-build from pom.xml

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog-plugin-auth-sso#5]
### Problem description
There is `profile web-interface-build` section in pom.xml, which requires graylog sources to build.
This should be made optional or removed totaly.

### Environment
* Plugin Version:  snapshot

**Comment by kroepke** [comment]
This is currently required for plugin builds, sorry.

**Comment by kroepke** [comment]
Context: UI plugins currently rely on the sources to be present

**Comment by hc4** [comment]
But i've removed whole profiles section and everything builds fine
