### ISSUE TITLE
Working nginx config with token passthrough

### ISSUE THREAD

**Issue by libussa** [Graylog2/graylog-plugin-auth-sso#51]
Hello,
I'm using `auth_request` with my auth service (vouch proxy)
I want users to still bhe able to use tokens with the graylog api, as well as sessions. Hence nginx should filter requests and only trigger authentication when no tokens or sessions are present.
Has anyone faced this use case? And if so, would you share your config?

Thanks!

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
