### ISSUE TITLE
gitlab auth

### ISSUE THREAD

**Issue by masikmos** [Graylog2/graylog-plugin-auth-sso#65]
Some one do gitlab auth with this module???

**Comment by kroepke** [comment]
This module will be deprecated and isn't suitable for integrating external identity providers.
I'm going to close it because we have no current plans on extending this plugin.

Thanks!

**Comment by oscarlofwenhamn** [comment]
@kroepke Are there any plans for a replacement or similarly for functionality related to external authentication to be built into the Graylog core application? Knowing where to follow progress and possibly aiding development would be great.
