### ISSUE TITLE
Configuration SSO

### ISSUE THREAD

**Issue by teamrussia** [Graylog2/graylog-plugin-auth-sso#67]
### Problem description
Hi..

I didn't understand how the plugin works. I tried to make a connection for him but I couldn't. Can you help me? Here is my configuration to analyze and how I tried to execute.
### Steps to reproduce the problem

![image](https://user-images.githubusercontent.com/55244524/94069376-dfe68580-fdc6-11ea-8dd7-9fddb10199c7.png)

Command:
curl -i -X POST -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'X-Requested-By: cli' -H 'Remote-User: myuser' 'http://10.56.7.87:9000/api/system/sessions' -d '{"username":"myuser", "password":"mypass"}'

![image](https://user-images.githubusercontent.com/55244524/94069632-4ec3de80-fdc7-11ea-8583-8db29f163b7f.png)

**Comment by florianpopp** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
