### ISSUE TITLE
Information regarding deprecation

### ISSUE THREAD

**Issue by oscarlofwenhamn** [Graylog2/graylog-plugin-auth-sso#68]
> This module will be deprecated and isn't suitable for integrating external identity providers.
> I'm going to close it because we have no current plans on extending this plugin.
>
> Thanks!

_Originally posted by @kroepke in https://github.com/Graylog2/graylog-plugin-auth-sso/issue_comments/688282928_

Information regarding deprecation should be added to the README to prevent confusion. 
Further, are there any plans for a replacement or similarly for functionality related to external authentication to be built into the Graylog core application?
Knowing where to follow progress and possibly aiding development would be great.

**Comment by kroepke** [comment]
@oscarlofwenhamn Sorry for the terse comment, was a bit busy at that moment.

The functionality is going to be in the standard server starting in 4.0, the (already merged) PR is https://github.com/Graylog2/graylog2-server/pull/9278

The background is that the implementation of this plugin is based on has changed significantly, and this plugin was awkward to maintain.

Long story short, it's in Graylog 4.0 by default.

**Comment by oscarlofwenhamn** [comment]
@kroepke Great, thanks for taking the time to clarify, much appreciated!
(Also, great news that this stellar feature will be added to the core service!)
