### ISSUE TITLE
This plugin will not be compatible with Graylog 4.0 and later!

### ISSUE THREAD

**Issue by glenjamin** [Graylog2/graylog-plugin-auth-sso#71]
Hello

I was hoping to get a bit more detail about the statement recently added to the README about 4.0 support. Does this mean that 4.0 will never be supported by this plugin?

Is there an alternative way to integrate with proxy-based SSO systems in 4.0?

**Comment by jalogisch** [comment]
From: https://docs.graylog.org/en/4.0/pages/upgrade/graylog-4.0.html#sso-authentication-plugin

> The core feature of the old SSO plugin (trusted HTTP header authentication) got integrated in the server.

**Comment by glenjamin** [comment]
Thanks!

**Comment by cameronattard** [comment]
@jalogisch any chance the integrated feature could be updated to have feature parity with this plugin? Particularly https://github.com/Graylog2/graylog2-server/issues/9714.

**Comment by jalogisch** [comment]
any feature that is not given needs a feature issue - as this moved into the core, you should create a feature request over at the graylog-server repo.
