### ISSUE TITLE
Graylog GUI isn't working after SSO plugin installed

### ISSUE THREAD

**Issue by smolit** [Graylog2/graylog-plugin-auth-sso#74]
Hello Communnity,
I tried to install the SSO Plugin to my Graylog test setup.
After copying the jar file to the plugin folder the Graylog GUI dosn't work.
The only log entry I can find is:
graylog-server[16756]: Exception in thread "main" java.lang.NoClassDefFoundError: org/graylog2/security/realm/LdapUserAuthenticator
and
graylog-server[16756]: Caused by: java.lang.ClassNotFoundException: org.graylog2.security.realm.LdapUserAuthenticator

Currently I am using LDAP as authentication service.

I have no idea what problem here occures and wold be happy if I can get any help.

Thanks Sebastian

### Steps to reproduce the problem
1. copy the jar file to the plugin folder
2. restart graylog-server service

### Environment
* Graylog Version: 4.0.5+d95b909
* Plugin Version: 3.3.0
* Elasticsearch Version: 7.10.2
* MongoDB Version: 4.0.23
* Operating System: ubuntu1804
* Browser version:  Microsoft Edge Version 89.0.774.50, Firefox 86.0.1 (64-bit)

**Comment by bernd** [comment]
@smolit As stated in the README, the SSO plugin is not compatible with Graylog 4.0.

The core functionality (HTTP header authentication) is now included in the server since 4.0.

**Comment by smolit** [comment]
Oh! I am sorry. I should read the README more carefully ;-)
