### ISSUE TITLE
Is there a 4.X version planned ?

### ISSUE THREAD

**Issue by quick691fr** [Graylog2/graylog-plugin-auth-sso#82]
### Problem description

Unable to find a SSO plugin for Graylog 4.X

### Steps to reproduce the problem

N/A

### Environment

* Graylog Version: 4.1.2
* Plugin Version: 3.3.0
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by getvivekv** [comment]
Its already built-in from GL 4 version

**Comment by kroepke** [comment]
This plugin is no longer updated for 4.x as the core functionality is in the server core and some role and permission details have changed making it incompatible.

We will be archiving this repository soon.
